name: "Setup GitHub Runner"
description: "Registers an EC2 instance as a self-hosted runner using SSM"

inputs:
  instance_id:
    required: true
    type: string
  self_hosted_pat:
    required: true
    type: string

outputs:
  runner_name:
    description: "Self-hosted Runner Name"
    value: ${{ steps.set-runner-name.outputs.runner_name }}

runs:
  using: "composite"
  steps:
     - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ inputs.aws_access_key_id }}
        aws configure set aws_secret_access_key ${{ inputs.aws_secret_access_key }}
        aws configure set region us-east-1
      shell: bash
    - name: Fetch GitHub Runner Token
      id: get-token
      run: |
        RUNNER_TOKEN=$(curl -X POST -H "Authorization: Bearer ${{ inputs.self_hosted_pat }}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/conveytopraveenkumar/cic-amino/actions/runners/registration-token | jq -r '.token')
        echo "RUNNER_TOKEN=$RUNNER_TOKEN" >> $GITHUB_ENV
      shell: bash

    - name: Generate Dynamic Runner Name
      id: set-runner-name
      run: |
        RUNNER_NAME="self-hosted-runner-$(date +%Y%m%d%H%M%S)"
        echo "RUNNER_NAME=$RUNNER_NAME" >> $GITHUB_ENV
        echo "runner_name=$RUNNER_NAME" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup GitHub Runner on EC2 via SSM
      run: |
        aws ssm send-command \
        --document-name "AWS-RunShellScript" \
        --targets '[{"Key":"instanceids","Values":["INSTANCE_ID"]}]' \
        --parameters '{
          "commands":[
            "mkdir -p /home/ubuntu/actions-runner && cd /home/ubuntu/actions-runner",
            "curl -o actions-runner-linux-x64.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz",
            "tar xzf ./actions-runner-linux-x64.tar.gz",
            "./config.sh --url https://github.com/conveytopraveenkumar/cic-amino --token $RUNNER_TOKEN --name $RUNNER_NAME --labels aws,ec2,linux,aosp-runner,android-build --work /home/ubuntu/runner_work --runnergroup Default",
            "nohup ./run.sh > runner.log 2>&1 &"
          ]
        }' \
        --region us-east-1
      shell: bash
