name: do-the-job
on:
  push:
    branches:
      - master

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: conveytopraveenkumar/ec2-github-runner@v1
        with:
          mode: start  # Ensures the EC2 runner is launched properly
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0f9de6e2d2f067fca
          ec2-instance-type: t3.micro
          subnet-id: subnet-089b826030629808d
          security-group-id: sg-04b81fc613de74b2a
          key-name: new-key
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]

  do-the-job:
    name: Execute tasks on EC2 self-hosted runner
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}  # Runs on the newly created EC2 runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: conveytopraveenkumar/cic-amino

      - name: Run Test Command
        run: |
          echo "Running job on self-hosted EC2 runner!"
          mkdir -p /home/ubuntu/build-output
          echo "Job completed successfully!" > /home/ubuntu/build-output/result.txt

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - do-the-job
    runs-on: ubuntu-latest
    if: ${{ always() }}  # Ensures the runner stops even if the job fails
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 runner
        uses: ec2-github-runner@v1
        with:
          mode: stop  # Ensures the EC2 runner is properly stopped
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
