name: Setup AWS EC2 as GitHub Runner and Initialize AOSP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup_aosp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Launch EC2 Instance
        run: |
          INSTANCE_ID=$(aws ec2 run-instances --image-id ami-09eb231ad55c3963d \
            --count 1 --instance-type t2.micro \
            --iam-instance-profile Name=EC2SSMInstanceProfile1 \
            --key-name new-key \
            --security-group-ids sg-0226bb335bbecbf05 \
            --subnet-id subnet-089b826030629808d \
            --query "Instances[0].InstanceId" --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Wait for EC2 Instance to Start
        run: aws ec2 wait instance-running --instance-ids $INSTANCE_ID

      - name: Ensure EC2 Instance Is Fully Initialized
        run: |
          while true; do
            INSTANCE_STATE=$(aws ec2 describe-instance-status --instance-ids $INSTANCE_ID --query "InstanceStatuses[0].InstanceState.Name" --output text)
            SYSTEM_STATUS=$(aws ec2 describe-instance-status --instance-ids $INSTANCE_ID --query "InstanceStatuses[0].SystemStatus.Status" --output text)
            INSTANCE_STATUS=$(aws ec2 describe-instance-status --instance-ids $INSTANCE_ID --query "InstanceStatuses[0].InstanceStatus.Status" --output text)

            echo "Current State: $INSTANCE_STATE | System Status: $SYSTEM_STATUS | Instance Status: $INSTANCE_STATUS"

            if [[ "$INSTANCE_STATE" == "running" && "$SYSTEM_STATUS" == "ok" && "$INSTANCE_STATUS" == "ok" ]]; then
              echo "Instance is fully initialized!"
              break
            fi
            sleep 10
          done

      - name: Install Dependencies and GitHub Runner
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "[{\"Key\":\"InstanceIds\",\"Values\":[\"$INSTANCE_ID\"]}]" \
            --parameters '{"commands":[
              "sudo apt update && sudo apt install -y unzip git repo",
              "curl -o awscliv2.zip \"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\"",
              "unzip awscliv2.zip",
              "sudo ./aws/install",
              "aws --version || { echo \"AWS CLI installation failed!\"; exit 1; }",
              "repo --version || { echo \"Repo installation failed!\"; exit 1; }",
      
              "mkdir -p /home/ubuntu/actions-runner",
              "cd /home/ubuntu/actions-runner",
      
              "curl -o actions-runner-linux-x64.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz",
              "tar xzf ./actions-runner-linux-x64.tar.gz",
      
              "sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner",
              "sudo chmod -R 755 /home/ubuntu/actions-runner",
      
              "./config.sh --url https://github.com/conveytopraveenkumar/cic-amino --token $RUNNER_TOKEN || { echo \"Runner config failed!\"; exit 1; }",
              
              "./run.sh || { echo \"Runner execution failed!\"; exit 1; }"
            ]}' \
            --region us-east-1

      - name: Tag EC2 Instance as GitHub Runner
        run: aws ec2 create-tags --resources $INSTANCE_ID --tags Key=Name,Value=GitHubRunner

  run_aosp_setup:
    needs: setup_aosp
    runs-on: self-hosted
    steps:
      - name: Initialize AOSP Repo
        run: |
          mkdir -p /home/ubuntu/aosp && cd /home/ubuntu/aosp
          repo init -u https://android.googlesource.com/platform/manifest 2>&1 | tee /home/ubuntu/aosp/repo-init.log

      - name: Sync AOSP Repo
        run: |
          for i in {1..3}; do repo sync -c 2>&1 | tee -a /home/ubuntu/aosp/repo-sync.log && break || sleep 30; done
