name: AMINO CICD WORKFLOW

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write


jobs:
  environment_setup:
    runs-on: ubuntu-latest
    permissions:
       id-token: write
       packages: write
    outputs:
      instance_ip: ${{ steps.env-setup.outputs.instance_ip }}
      instance_id: ${{ steps.env-setup.outputs.instance_id }}
      runner_name: ${{ steps.env-setup.outputs.runner_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install yq (YAML Processor)
        run: |
          sudo apt update && sudo apt install -y yq
      - name: Load Variables from YAML
        run: |
          echo "PROJECT_NAME=$(yq '.project_name' .github/variables.yml)" >> $GITHUB_ENV
          echo "BUILD_TYPE=$(yq '.build_type' .github/variables.yml)" >> $GITHUB_ENV
          echo "TESTING=$(yq '.testing' .github/variables.yml)" >> $GITHUB_ENV
          echo "MANIFEST_URL=$(yq '.manifest_url' .github/variables.yml)" >> $GITHUB_ENV
          echo "BRANCH=$(yq '.branch' .github/variables.yml)" >> $GITHUB_ENV
          echo "BUILD_COMMANDS=$(yq '.build_commands' .github/variables.yml)" >> $GITHUB_ENV

      - name: Use Composite Action for Setup
        id: env-setup
        uses: ./.github/actions/amino-composite-action
        with:
          project_name: "${{ env.PROJECT_NAME }}"
          build_type: "${{ env.BUILD_TYPE }}"
          manifest_url: "${{ env.MANIFEST_URL }}"
          branch: "${{ env.BRANCH }}"
          build_commands: "${{ env.BUILD_COMMANDS }}"
          self_hosted_pat: ${{ secrets.SELF_HOSTED_PAT }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  compilation_on_runner:
    needs: environment_setup
    runs-on: [self-hosted, aws, ec2, linux, aosp-runner, oidc]
    permissions:
       id-token: write
       packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Debug Runner Name
        run: |
          echo "Loaded Runner Name: ${{ needs.environment_setup.outputs.runner_name }}"
      - name: Install yq (YAML Processor)
        run: |
          sudo apt update && sudo snap install -y yq
      - name: Load Variables from YAML
        run: |
          echo "PROJECT_NAME=$(yq '.project_name' .github/variables.yml)" >> $GITHUB_ENV
          echo "BUILD_TYPE=$(yq '.build_type' .github/variables.yml)" >> $GITHUB_ENV
          echo "TESTING=$(yq '.testing' .github/variables.yml)" >> $GITHUB_ENV
          echo "MANIFEST_URL=$(yq '.manifest_url' .github/variables.yml)" >> $GITHUB_ENV
          echo "BRANCH=$(yq '.branch' .github/variables.yml)" >> $GITHUB_ENV
          echo "BUILD_COMMANDS=$(yq '.build_commands' .github/variables.yml)" >> $GITHUB_ENV
      - name: Use Compilation Action
        uses: ./.github/actions/amino-compilation-action
        with:
          project_name: "${{ env.PROJECT_NAME }}"
          build_type: "${{ env.BUILD_TYPE }}"
          manifest_url: "${{ env.MANIFEST_URL }}"
          branch: "${{ env.BRANCH }}"
          build_commands: "${{ env.BUILD_COMMANDS }}"
          runner_name: "${{ needs.environment_setup.outputs.runner_name }}"
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          githubtoken: ${{ secrets.GITHUB_TOKEN }}
          awssshkey: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

          
