name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  launch-ec2:
    uses: ./.github/workflows/launch-ec2.yml
    with:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }

  setup-self-hosted-runner:
    needs: launch-ec2
    uses: ./.github/workflows/setup-self-hosted-runner.yml
    with:
      instance_id: ${{ needs.launch-ec2.outputs.instance_id }}
      instance_ip: ${{ needs.launch-ec2.outputs.instance_ip }}

  Compilation-on-self-hosted:
    needs: setup-self-hosted-runner
    uses: ./.github/workflows/compilation-on-self-hosted.yml
