name: AMINO BUILD AND DEPLY 
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Project name'
        required: true
      build_type:
        description: 'Build type (e.g., userdebug)'
        required: true
      manifest_url:
        description: 'Manifest repository URL'
        required: true
      branch:
        description: 'Branch name'
        required: true
      build_commands:
        description: 'Build commands'
        required: true

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  environment_setup:
    runs-on: ubuntu-latest
    permissions:
       id-token: write
       packages: write
    outputs:
      instance_ip: ${{ steps.env-setup.outputs.instance_ip }}
      instance_id: ${{ steps.env-setup.outputs.instance_id }}
      runner_name: ${{ steps.env-setup.outputs.runner_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install yq (YAML Processor)
        run: |
          sudo apt update && sudo apt install -y yq
      - name: Load Variables from YAML
        run: |
          echo "PROJECT_NAME=${{ github.event.inputs.project_name }}" >> $GITHUB_ENV
          echo "BUILD_TYPE=${{ github.event.inputs.build_type }}" >> $GITHUB_ENV
          echo "MANIFEST_URL=${{ github.event.inputs.manifest_url }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          echo "BUILD_COMMANDS=${{ github.event.inputs.build_commands }}" >> $GITHUB_ENV

      - name: Use Composite Action for Setup
        id: env-setup
        uses: ./.github/actions/amino-composite-action
        with:
          project_name: "${{ env.PROJECT_NAME }}"
          build_type: "${{ env.BUILD_TYPE }}"
          manifest_url: "${{ env.MANIFEST_URL }}"
          branch: "${{ env.BRANCH }}"
          build_commands: "${{ env.BUILD_COMMANDS }}"
          self_hosted_pat: ${{ secrets.SELF_HOSTED_PAT }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  compilation_on_runner:
    needs: environment_setup
    runs-on: [self-hosted, aws, ec2, linux, aosp-runner, oidc]
    permissions:
       id-token: write
       packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Debug Runner Name
        run: |
          echo "Loaded Runner Name: ${{ needs.environment_setup.outputs.runner_name }}"
      - name: Install yq (YAML Processor)
        run: |
          sudo apt update && sudo snap install yq
      - name: Load Variables from YAML
        run: |
          echo "PROJECT_NAME=${{ github.event.inputs.project_name }}" >> $GITHUB_ENV
          echo "BUILD_TYPE=${{ github.event.inputs.build_type }}" >> $GITHUB_ENV
          echo "MANIFEST_URL=${{ github.event.inputs.manifest_url }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          echo "BUILD_COMMANDS=${{ github.event.inputs.build_commands }}" >> $GITHUB_ENV

      - name: Use Compilation Action
        uses: ./.github/actions/amino-compilation-action
        with:
          project_name: "${{ env.PROJECT_NAME }}"
          build_type: "${{ env.BUILD_TYPE }}"
          manifest_url: "${{ env.MANIFEST_URL }}"
          branch: "${{ env.BRANCH }}"
          build_commands: "${{ env.BUILD_COMMANDS }}"
          runner_name: "${{ needs.environment_setup.outputs.runner_name }}"
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          githubtoken: ${{ secrets.GITHUB_TOKEN }}
          awssshkey: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
