name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  launch-ec2:
    uses: ./.github/workflows/launch-ec2.yml

  setup-self-hosted-runner:
    needs: launch-ec2
    uses: ./.github/workflows/setup-self-hosted-runner.yml
    with:
      instance_id: ${{ needs.launch-ec2.outputs.instance_id }}
      instance_ip: ${{ needs.launch-ec2.outputs.instance_ip }}

  Compilation-on-self-hosted:
    needs: setup-self-hosted-runner
    uses: ./.github/workflows/Compilation-on-self-hosted.yml
