name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  launch-ec2:
    uses: ./.github/workflows/launch-ec2.yml

  setup-self-hosted-runner:
    needs: launch-ec2
    uses: ./.github/workflows/setup-self-hosted-runner.yml

  aosp-build:
    needs: setup-self-hosted-runner
    uses: ./.github/workflows/aosp-build.yml
