name: Main Workflow

on:
  push:
    branches:
      - dev2

jobs:
  launch-ec2:
    uses: ./.github/workflows/launch-ec2.yaml

  setup-runner:
    needs: launch-ec2
    uses: ./.github/workflows/setup-runner.yaml
    with:
      instance_ip: ${{ needs.launch-ec2.outputs.instance_ip }}
      instance_id: ${{ needs.launch-ec2.outputs.instance_id }}

  build:
    needs: setup-runner
    uses: ./.github/workflows/build.yaml
    with:
      instance_id: ${{ needs.setup-runner.inputs.instance_id }}
